name: IntegrationTest
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'docs/**'
  schedule:
      - cron: '24 22 * * 0'

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: Surrogates.jl, group: All}
          - {user: SciML, repo: NeuralPDE.jl, group: NNPDE1}
          - {user: SciML, repo: NeuralPDE.jl, group: NNPDE2}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      julia-version: "1"
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
